# Generated by Django 4.0.5 on 2022-06-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(default='a', max_length=100),
        ),
    ]
